# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398ac3422cd9e0e7a4a05057bb873984717fb876b62549417fb1e9fdc49f91e5187885ce5790d7845a2a941c96d4d7e7f698b342da51e58860d0e070fbf5210a

test:
  secret_key_base: deebd492482b4d4f7ea8a23703ed0f30fec8e46b4f9c5b5c3bf602c5e2ebef98ad47f4c06dc3b0e9da548e873bc835626f88a15f0fd1a19951af907d2bd4c897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
